### ISSUE TITLE
I get this just on using H5file

### ISSUE THREAD

**Issue by clive-g-brown** [Vindaar/nimhdf5#27]
could not import: H5Oget_info

**Comment by Vindaar** [comment]
Hey! 
That issue stems from the fact that you compiled the library against a different HDF5 version than expected (see also here: https://github.com/Vindaar/nimhdf5#compatibility; and sorry, the README has to be updated...).

By default if you just compile a project using `nimhdf5` the library expects a HDF5 version of `1.10.1` / `1.10.2`. I'm uncertain, which version mismatch causes the error you see right now. I believe that's due to a change from `1.10.2` to `1.10.3`.

In any case, the problem should go away if compile either with
`-d:H5_FUTURE` (in case I remember correctly)
or `-d:H5_LEGACY` (in case it was actually a change from `1.8` to `1.10`). 

I hope that solves it for you!

**Comment by clive-g-brown** [comment]
yes that works, thanks

**Comment by Vindaar** [comment]
Glad to hear. If there's anything else, feel free to open another issue! 
I added a note to the README about the explicit errors one may encounter.
